# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: openapi/openapi.yaml
theme.openapi:
  htmlTemplate: ./docs/dev.html
  theme:
    colors:
      primary:
        main: "#32329f"
